#version 450

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
layout(constant_id = 0) const uint NX = 128u;
layout(constant_id = 1) const uint NY = 128u;

layout(std430, binding = 0) buffer UField { float data[]; } u;
layout(std430, binding = 1) buffer VField { float data[]; } v;
layout(std430, binding = 11) buffer ForceField { uint data[]; } force;

// ---------- 主函数：施加累加的力到速度场并清零 ----------
void main() {
    uint gidx = gl_GlobalInvocationID.x;
    if (gidx >= NX * NY) return;

    float fu = uintBitsToFloat(force.data[gidx * 2u]);
    float fv = uintBitsToFloat(force.data[gidx * 2u + 1u]);

    u.data[gidx] += fu;
    v.data[gidx] += fv;

    force.data[gidx * 2u] = 0u;
    force.data[gidx * 2u + 1u] = 0u;
}